---

- import_tasks: debian.yml
  when: ansible_distribution in ['Ubuntu', 'Debian']

- import_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- name: Create directory for config
  file:
    path: /etc/influxdb
    state: directory
    owner: root
    group: root
    mode: 0744
  notify: influxdb started

- name: Replace location of config
  replace:
    path: /etc/default/influxdb2
    regexp: '^(INFLUXD_CONFIG_PATH=).*'
    replace: '\1{{ influxdb_config_path }}'
  notify: influxdb started

- name: Create influxdb options
  set_fact:
    influxdb_options: "{{ influxdb_config_options }}"

- name: Create configuration file
  copy:
    content: "{{ influxdb_options | to_nice_yaml }}"
    dest: "{{ influxdb_config_path }}"
    owner: root
    group: root
    mode: 0644
  notify: influxdb started

- import_tasks: create-admin.yml
  when: influxdb_admin_user_password is defined

- include_tasks: create-user.yml
  loop: "{{ influxdb_users }}"
