---
- import_tasks: debian.yml
  when: ansible_distribution in ['Ubuntu', 'Debian']

- import_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- name: Set up template file
  template:
    src: templates/influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
  notify:
    - influxdb started
    - influxdb restarted

- import_tasks: create-admin.yml
  when: influxdb_admin_user_password is defined
