---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check that influx config exists
      stat:
        path: /etc/influxdb/config.yml
      register: p

    - name: Assert existence of file
      assert:
        that: p.stat.exists

    - name: Assert owner is influxdb
      assert:
        that: p.stat.pw_name == "influxdb"

    - name: Assert group is influxdb
      assert:
        that: p.stat.gr_name == "influxdb"

    - name: Enable service
      systemd:
        name: influxd
        enabled: true
      register: system

    - name: Assert service is enabled
      assert:
        that: not system.changed

    - name: Start service
      systemd:
        name: influxd
        state: started
      register: started_influx

    - name: Assert service was running
      assert:
        that: not started_influx.changed
